<a href="https://colab.research.google.com/github/lsmyk/libraryJuiceAcademyAssignment/blob/main/Week_1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ### Larisa Smyk


Please add your name to this markdown cell.

## Submitting your homework!

Two steps are required for this week's homework once you have completed it:

- __Share__ this notebook with _libraryjuicepresspython@gmail.com_ so it can be marked in Colab
- __Print as PDF__ and upload to the the week's homework submission location on the Library Juice Academy LMS

# Advanced Python - Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [ ]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [ ]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://lis-info671-fall2023.github.io/group2-amlit/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [ ]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "A scene from the stage production of A Raisin in the Sun",
  "creator": "Friedman-Abeles (Firm)",
  "date": "1959",
  "description": "Claudia McNeil, Sidney Poitier and Diana Sands in the stage production A Raisin in the Sun",
  "subject": "Housing Discrimination; African-Americans; Theatrical productions; Hansberry, Lorraine, 1930-1965",
  "location": "New York City, New York, United States",
  "source": "Courtesy of the New York Public Library https://digitalcollections.nypl.org/items/b0dae162-20b6-2b00-e040-e00a1806276d",
  "identifier": "rs_2",
  "type": "Image; StillImage",
  "format": "image/jpeg",
  "language": "eng",
  "rights": "Educational Use",
  "rightsstatement": "https://rightsstatements.org/page/InC-EDU/1.0/?language=en",
  "reference_url": "https://lis-info671-fall2023.github.io/group2-amlit/item.html?id=amlit007"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [ ]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://lis-info671-fall2023.github.io/group2-amlit/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [ ]:
print(json.dumps(total_facet_data,indent=2))

{
  "facets": [
    {
      "field": "subject",
      "terms": {
        "african american civil rights workers": 2,
        "african-american families": 1,
        "african-american literature": 1,
        "african-americans": 10,
        "automobiles": 1,
        "baldwin, james, 1924-1987": 1,
        "california": 1,
        "chicago": 1,
        "children": 1,
        "civil rights": 3,
        "civil rights movement": 1,
        "civil rights movement in tennessee": 1,
        "discrimination": 1,
        "draft": 1,
        "drama": 1,
        "du bois, w. e. b. (william edward burghardt), 1868-1963": 1,
        "dublin": 1,
        "ellison, ralph 1914-1994": 1,
        "garvey, marcus, 1887-1940": 1,
        "great depression": 1,
        "hansberry, lorraine, 1930-1965": 1,
        "harding, warren g. (warren gamaliel), 1865-1923": 1,
        "housing": 1,
        "housing discrimination": 3,
        "king, martin luther, jr., 1929-1968": 1,
        "law enforcement": 2,
        "minstrel shows": 1,
        "oral history": 1,
        "performing arts posters": 1,
        "prohibition": 1,
        "protests": 1,
        "race relations": 8,
        "racial discrimination": 1,
        "scottsboro trial": 2,
        "segregation": 1,
        "theatrical productions": 2,
        "urbanization, discrimination, migration": 1,
        "white supremacy movements": 1,
        "world war, 1939-1945 african americans": 1,
        "world war, 1939-1945 united states": 1,
        "x, malcolm, 1925-1965": 1
      }
    },
    {
      "field": "creator",
      "terms": {
        "barnes, dr.": 1,
        "chicago commission": 1,
        "cincinnati and new york: the strobridge lithographic company": 1,
        "du bois, w. e. b.": 1,
        "ellison, ralph": 1,
        "endore, guy": 1,
        "engelhardt, tom": 1,
        "friedman-abeles (firm)": 1,
        "hamrick, peggy": 1,
        "hansberry, lorraine": 1,
        "henry romeike clipping service": 1,
        "jackson, rosa": 1,
        "king, martin luther, jr.": 1,
        "pfaff, eugene": 1,
        "scottsboro defense committee": 1,
        "shorter, charles, a": 1,
        "the atlanta journal-constitution": 1,
        "the dick cavett show": 1,
        "unknown": 2,
        "unknown (personal donation to la public library)": 1,
        "urban league of philadelphia": 1,
        "wsb-tv (television station : atlanta, ga.)": 1
      }
    },
    {
      "field": "format",
      "terms": {
        "application/pdf": 8,
        "audio/mp3": 1,
        "image/jpeg": 1,
        "image/png": 8,
        "video/mp4": 2
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below

Facets in my site are:
- facet 1 is "subject"
- facet 2 is "creator"
- facet 3 is "format"

In [ ]:
#count frequency of facets usage

for facet in total_facet_data["facets"]:
    print(
        facet["field"],
        len(facet["terms"])
    )

subject 41
creator 22
format 5


The facet that shows up the most is subject. It is used 41 times on my selected site

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [ ]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized = pd.json_normalize(cb_data['objects'])
cb_normalized

,title,creator,date,description,subject,location,latitude,longitude,source,identifier,type,format,language,rights,rightsstatement,reference_url
0,A “whites only” restroom sign,Unknown,1964,Signs like this one commonly marked segregated...,Segregation; African-Americans; Civil rights,"Georgia, United States",33.346678,-84.119434,Courtesy Susan Ketcham of East Central High Sc...,tkm_1,Image; StillImage,image/png,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
1,Interview with Rosa Jackson,"Jackson, Rosa; Hamrick, Peggy",1984-07-23,An excerpt from a 1984 interview with Rosa Jac...,African-Americans; Law Enforcement; Prohibition,"Alabama, United States",32.3182,-86.9023,Courtesy Susan Ketcham of East Central High Sc...,tkm_2,Sound,audio/mp3,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
2,"""Save the Scottsboro"" Boys",Scottsboro Defense Committee,1931,"Flyer announcing a rally in support of the ""Sc...",Scottsboro Trial; African-Americans; Civil rights,"Scottsboro, Alabama, United States",34.6723,-86.0341,Courtesy Susan Ketcham of East Central High Sc...,tkm_3,Image; StillImage,image/png,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
3,A photograph of kids and a new car,Unknown,1935,The purchase of a new car is a proud day for a...,Automobiles; California; Dublin; Children; Gre...,"Dublin, California, United States",37.7159,-121.9101,Courtesy Susan Ketcham of East Central High Sc...,tkm_4,Image; StillImage,image/png,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
4,Excerpt of The Crime at Scottsboro by Guy Endore,"Endore, Guy",1938,An excerpt from The Crime at Scottsboro by Guy...,Scottsboro Trial; African-Americans; Civil rights,"Hollywood, California, United States",34.0928,-118.3287,Courtesy Susan Ketcham of East Central High Sc...,tkm_5,Text,application/pdf,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
5,An excerpt from a Chicago commission report,Chicago Commission,1943,An excerpt from a Chicago commission report on...,"Chicago; Urbanization, Discrimination, Migration","Chicago, Illinois, United States",41.8781,-87.6298,Courtesy of Frank Abbott and the DPLA https://...,rs_1,Text,application/pdf,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
6,A scene from the stage production of A Raisin ...,Friedman-Abeles (Firm),1959,"Claudia McNeil, Sidney Poitier and Diana Sands...",Housing Discrimination; African-Americans; The...,"New York City, New York, United States",NaN,NaN,Courtesy of the New York Public Library https:...,rs_2,Image; StillImage,image/jpeg,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
7,Image of the playbook cover of A Raisin in the...,"Hansberry, Lorraine",1959,Play about a black family's experiences in a C...,African-American Literature; Theatrical produc...,"Chicago, Illinois, United States",41.8781,-87.6298,Courtesy of Frank Abbott and the DPLA https://...,rs_3,Image; StillImage,image/png,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
8,Come On In – This Is An Integrated Neighborhood,"Engelhardt, Tom",1967-05-28,A 1967 political cartoon about war and residen...,Housing Discrimination; African-Americans; Rac...,"Columbia, Missouri, United States",38.94872885,-92.3303072443813,Courtesy of Frank Abbott and the DPLA https://...,rs_4,Image; StillImage,image/png,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
9,Columbians threatening neighborhood,The Atlanta Journal-Constitution,1946,A photo of crowd gathered after a white suprem...,White Supremacy Movements; African-American Fa...,"Fulton County, Atlanta, Georgia, United States",33.749,-84.3798,Courtesy of Frank Abbott and the DPLA https://...,rs_5,Image; StillImage,image/png,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
10,Collage of newspaper clippings related to Afri...,Henry Romeike clipping service,1921,Includes a variety of newspaper clippings abou...,Race relations; African American civil rights ...,"Alabama, United States",32.3182,-86.9023,Courtesy of Jolie Sheffer of Bowling Green Sta...,im_1,Text,application/pdf,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
11,TQS from Invisible Man,"Ellison, Ralph",1952-04-14,"A typed quotation from Invisible Man, signed b...","Ellison, Ralph 1914-1994; African-Americans","Cambridge, Massachusetts, United States",42.373611,-71.110558,Courtesy of Jolie Sheffer of Bowling Green Sta...,im_2,Text,application/pdf,eng,Public Domain,https://rightsstatements.org/page/NoC-US/1.0/?...,https://lis-info671-fall2023.github.io/group2-...
12,An excerpt from The Souls of Black Folk by W.E...,"Du Bois, W. E. B.",1903,In this famous excerpt from The Souls of Black...,"Du Bois, W. E. B. (William Edward Burghardt), ...",United States,42.378036,-71.118340,Courtesy of Jolie Sheffer of Bowling Green Sta...,im_3,Text,application/pdf,eng,Public Domain,https://rightsstatements.org/page/NoC-US/1.0/?...,https://lis-info671-fall2023.github.io/group2-...
13,Re: The Negro Population of Philadelphia and S...,"Urban League of Philadelphia; Barnes, Dr.; Sho...",1939-10-25,The memo outlines key statistical differences ...,Race relations; Discrimination; Housing,"Philadelphia, Pennsylvania, United States",39.9526,-75.1652,Courtesy of Jolie Sheffer of Bowling Green Sta...,im_4,Text,application/pdf,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
14,Neil O'Brien Minstrels,Cincinnati and New York: The Strobridge Lithog...,1915,This particular image portrays Neil O'Brien (c...,Race Relations; Minstrel Shows; Performing Art...,"Alabama, United States",32.3182,-86.9023,Courtesy of Jolie Sheffer of Bowling Green Sta...,im_5,Image; StillImage,image/png,eng,Public Domain,https://rightsstatements.org/page/NoC-US/1.0/?...,https://lis-info671-fall2023.github.io/group2-...
15,Malcolm X on Birmingham Riots,"WSB-TV (Television station : Atlanta, Ga.)",1963-05-16,A video clip in which Malcolm X condemns Presi...,"Race relations; X, Malcolm, 1925-1965; African...","Birmingham, Alabama, United States",33.5186,-86.8104,Courtesy of Samanthan Gibson and the DPLA http...,fnt_1,moving image,video/mp4,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
16,James Baldwin discusses racism,The Dick Cavett Show,1969-05-16,James Baldwin has an open discussion of racial...,Race relations; Civil Rights Movement; African...,"New York City, New York, United States",NaN,NaN,Courtesy of The Dick Cavett Show https://www.y...,fnt_2,moving image,video/mp4,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
17,An excerpt from a 1982 oral history interview ...,"Pfaff, Eugene",1982-09-15,A portion of a transcribed oral history interv...,"Race relations; Baldwin, James, 1924-1987; Ora...","Greensboro, North Carolina, United States",36.1359,-79.8702,Courtesy of Samanthan Gibson and the DPLA http...,fnt_3,Text,application/pdf,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
18,A photograph of four African American World Wa...,unknown (personal donation to LA Public Library),1944,A black and white photograph of four African A...,"Draft; Race relations; World War, 1939-1945 Un...","Los Angeles, California, United States",34.052235,-118.2426,Courtesy of Samanthan Gibson and the DPLA http...,fnt_4,Image; StillImage,image/png,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
19,"""Letter from Birmingham Jail""","King, Martin Luther, Jr.",1963-04-16,"An excerpt from ""Letter from Birmingham City J...","King, Martin Luther, Jr., 1929-1968; Race rela...","Birmingham, Alabama, United States",33.5186,-86.8104,Courtesy of Samanthan Gibson and the DPLA http...,fnt_5,Text,application/pdf,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...

In [ ]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(5)

,title,creator,date,description,subject,location,latitude,longitude,source,identifier,type,format,language,rights,rightsstatement,reference_url
4,Excerpt of The Crime at Scottsboro by Guy Endore,"Endore, Guy",1938,An excerpt from The Crime at Scottsboro by Guy...,Scottsboro Trial; African-Americans; Civil rights,"Hollywood, California, United States",34.0928,-118.3287,Courtesy Susan Ketcham of East Central High Sc...,tkm_5,Text,application/pdf,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
5,An excerpt from a Chicago commission report,Chicago Commission,1943,An excerpt from a Chicago commission report on...,"Chicago; Urbanization, Discrimination, Migration","Chicago, Illinois, United States",41.8781,-87.6298,Courtesy of Frank Abbott and the DPLA https://...,rs_1,Text,application/pdf,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
18,A photograph of four African American World Wa...,unknown (personal donation to LA Public Library),1944,A black and white photograph of four African A...,"Draft; Race relations; World War, 1939-1945 Un...","Los Angeles, California, United States",34.052235,-118.2426,Courtesy of Samanthan Gibson and the DPLA http...,fnt_4,Image; StillImage,image/png,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
19,"""Letter from Birmingham Jail""","King, Martin Luther, Jr.",1963-04-16,"An excerpt from ""Letter from Birmingham City J...","King, Martin Luther, Jr., 1929-1968; Race rela...","Birmingham, Alabama, United States",33.5186,-86.8104,Courtesy of Samanthan Gibson and the DPLA http...,fnt_5,Text,application/pdf,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...
8,Come On In – This Is An Integrated Neighborhood,"Engelhardt, Tom",1967-05-28,A 1967 political cartoon about war and residen...,Housing Discrimination; African-Americans; Rac...,"Columbia, Missouri, United States",38.94872885,-92.3303072443813,Courtesy of Frank Abbott and the DPLA https://...,rs_4,Image; StillImage,image/png,eng,Educational Use,https://rightsstatements.org/page/InC-EDU/1.0/...,https://lis-info671-fall2023.github.io/group2-...

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [ ]:
# my dataframe shows objects, but question is about facets
cb_normalized[["subject","creator","format"]].count()

subject    20
creator    20
format     20
dtype: int64

In [ ]:
# to count subject fields:
cb_normalized["subject"].value_counts()

subject
Scottsboro Trial; African-Americans; Civil rights                                                                                    2
Segregation; African-Americans; Civil rights                                                                                         1
African-Americans; Law Enforcement; Prohibition                                                                                      1
Automobiles; California; Dublin; Children; Great Depression                                                                          1
Chicago; Urbanization, Discrimination, Migration                                                                                     1
Housing Discrimination; African-Americans; Theatrical productions; Hansberry, Lorraine, 1930-1965                                    1
African-American Literature; Theatrical productions; Drama                                                                           1
Housing Discrimination; African-Americans; Racial Discrimination                                                                     1
White Supremacy Movements; African-American Families; Housing Discrimination                                                         1
Race relations; African American civil rights workers; Garvey, Marcus, 1887-1940; Harding, Warren G. (Warren Gamaliel), 1865-1923    1
Ellison, Ralph 1914-1994; African-Americans                                                                                          1
Du Bois, W. E. B. (William Edward Burghardt), 1868-1963; African-Americans                                                           1
Race relations; Discrimination; Housing                                                                                              1
Race Relations; Minstrel Shows; Performing Arts Posters                                                                              1
Race relations; X, Malcolm, 1925-1965; African American civil rights workers;                                                        1
Race relations; Civil Rights Movement; African-Americans; Law Enforcement; Protests                                                  1
Race relations; Baldwin, James, 1924-1987; Oral history;                                                                             1
Draft; Race relations; World War, 1939-1945 United States; World War, 1939-1945 African Americans;                                   1
King, Martin Luther, Jr., 1929-1968; Race relations; African-Americans; Civil Rights Movement in Tennessee                           1
Name: count, dtype: int64

In [ ]:
# Since my subject fields contains multiple subjects per record, I need to separate them:
cb_normalized["subject"].str.split(";").explode().str.strip().value_counts()

subject
African-Americans                                          10
Race relations                                              7
Civil rights                                                3
Housing Discrimination                                      3
                                                            3
Scottsboro Trial                                            2
Theatrical productions                                      2
African American civil rights workers                       2
Law Enforcement                                             2
Prohibition                                                 1
Segregation                                                 1
Great Depression                                            1
Children                                                    1
Dublin                                                      1
California                                                  1
Automobiles                                                 1
Hansberry, Lorraine, 1930-1965                              1
Urbanization, Discrimination, Migration                     1
African-American Literature                                 1
Racial Discrimination                                       1
Drama                                                       1
African-American Families                                   1
White Supremacy Movements                                   1
Garvey, Marcus, 1887-1940                                   1
Harding, Warren G. (Warren Gamaliel), 1865-1923             1
Ellison, Ralph 1914-1994                                    1
Chicago                                                     1
Du Bois, W. E. B. (William Edward Burghardt), 1868-1963     1
Discrimination                                              1
Race Relations                                              1
Housing                                                     1
Minstrel Shows                                              1
Performing Arts Posters                                     1
X, Malcolm, 1925-1965                                       1
Civil Rights Movement                                       1
Protests                                                    1
Baldwin, James, 1924-1987                                   1
Oral history                                                1
Draft                                                       1
World War, 1939-1945 United States                          1
World War, 1939-1945 African Americans                      1
King, Martin Luther, Jr., 1929-1968                         1
Civil Rights Movement in Tennessee                          1
Name: count, dtype: int64

The subject that shows up the most is "African-American". It is used 10 times on my selected site


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.